micronaut:
  http:
    client:
      read-timeout: 600s

btcproxyd:
  rpcproxy:
    uri: http://localhost:18443
    username: setmeplease
    password: setmetooplease
    allow-list:
      - generate
      - generatetoaddress
      - getblockcount
      - getchaintips
      - gettxoutsetinfo
      - uptime
